In [2]:
import numpy as np
import pandas as pd

In [3]:
movies=pd.read_csv("tmdb_5000_movies.csv")
credit=pd.read_csv("tmdb_5000_credits.csv")

In [4]:
movies.head()

,budget,genres,homepage,id,keywords,original_language,original_title,overview,popularity,production_companies,production_countries,release_date,revenue,runtime,spoken_languages,status,tagline,title,vote_average,vote_count
0,237000000,"[{""id"": 28, ""name"": ""Action""}, {""id"": 12, ""nam...",http://www.avatarmovie.com/,19995,"[{""id"": 1463, ""name"": ""culture clash""}, {""id"":...",en,Avatar,"In the 22nd century, a paraplegic Marine is di...",150.437577,"[{""name"": ""Ingenious Film Partners"", ""id"": 289...","[{""iso_3166_1"": ""US"", ""name"": ""United States o...",2009-12-10,2787965087,162.0,"[{""iso_639_1"": ""en"", ""name"": ""English""}, {""iso...",Released,Enter the World of Pandora.,Avatar,7.2,11800
1,300000000,"[{""id"": 12, ""name"": ""Adventure""}, {""id"": 14, ""...",http://disney.go.com/disneypictures/pirates/,285,"[{""id"": 270, ""name"": ""ocean""}, {""id"": 726, ""na...",en,Pirates of the Caribbean: At World's End,"Captain Barbossa, long believed to be dead, ha...",139.082615,"[{""name"": ""Walt Disney Pictures"", ""id"": 2}, {""...","[{""iso_3166_1"": ""US"", ""name"": ""United States o...",2007-05-19,961000000,169.0,"[{""iso_639_1"": ""en"", ""name"": ""English""}]",Released,"At the end of the world, the adventure begins.",Pirates of the Caribbean: At World's End,6.9,4500
2,245000000,"[{""id"": 28, ""name"": ""Action""}, {""id"": 12, ""nam...",http://www.sonypictures.com/movies/spectre/,206647,"[{""id"": 470, ""name"": ""spy""}, {""id"": 818, ""name...",en,Spectre,A cryptic message from Bond’s past sends him o...,107.376788,"[{""name"": ""Columbia Pictures"", ""id"": 5}, {""nam...","[{""iso_3166_1"": ""GB"", ""name"": ""United Kingdom""...",2015-10-26,880674609,148.0,"[{""iso_639_1"": ""fr"", ""name"": ""Fran\u00e7ais""},...",Released,A Plan No One Escapes,Spectre,6.3,4466
3,250000000,"[{""id"": 28, ""name"": ""Action""}, {""id"": 80, ""nam...",http://www.thedarkknightrises.com/,49026,"[{""id"": 849, ""name"": ""dc comics""}, {""id"": 853,...",en,The Dark Knight Rises,Following the death of District Attorney Harve...,112.312950,"[{""name"": ""Legendary Pictures"", ""id"": 923}, {""...","[{""iso_3166_1"": ""US"", ""name"": ""United States o...",2012-07-16,1084939099,165.0,"[{""iso_639_1"": ""en"", ""name"": ""English""}]",Released,The Legend Ends,The Dark Knight Rises,7.6,9106
4,260000000,"[{""id"": 28, ""name"": ""Action""}, {""id"": 12, ""nam...",http://movies.disney.com/john-carter,49529,"[{""id"": 818, ""name"": ""based on novel""}, {""id"":...",en,John Carter,"John Carter is a war-weary, former military ca...",43.926995,"[{""name"": ""Walt Disney Pictures"", ""id"": 2}]","[{""iso_3166_1"": ""US"", ""name"": ""United States o...",2012-03-07,284139100,132.0,"[{""iso_639_1"": ""en"", ""name"": ""English""}]",Released,"Lost in our world, found in another.",John Carter,6.1,2124

In [5]:
credit.head()

,movie_id,title,cast,crew
0,19995,Avatar,"[{""cast_id"": 242, ""character"": ""Jake Sully"", ""...","[{""credit_id"": ""52fe48009251416c750aca23"", ""de..."
1,285,Pirates of the Caribbean: At World's End,"[{""cast_id"": 4, ""character"": ""Captain Jack Spa...","[{""credit_id"": ""52fe4232c3a36847f800b579"", ""de..."
2,206647,Spectre,"[{""cast_id"": 1, ""character"": ""James Bond"", ""cr...","[{""credit_id"": ""54805967c3a36829b5002c41"", ""de..."
3,49026,The Dark Knight Rises,"[{""cast_id"": 2, ""character"": ""Bruce Wayne / Ba...","[{""credit_id"": ""52fe4781c3a36847f81398c3"", ""de..."
4,49529,John Carter,"[{""cast_id"": 5, ""character"": ""John Carter"", ""c...","[{""credit_id"": ""52fe479ac3a36847f813eaa3"", ""de..."

In [6]:
credit.head(1)["cast"].values

array(['[{"cast_id": 242, "character": "Jake Sully", "credit_id": "5602a8a7c3a3685532001c9a", "gender": 2, "id": 65731, "name": "Sam Worthington", "order": 0}, {"cast_id": 3, "character": "Neytiri", "credit_id": "52fe48009251416c750ac9cb", "gender": 1, "id": 8691, "name": "Zoe Saldana", "order": 1}, {"cast_id": 25, "character": "Dr. Grace Augustine", "credit_id": "52fe48009251416c750aca39", "gender": 1, "id": 10205, "name": "Sigourney Weaver", "order": 2}, {"cast_id": 4, "character": "Col. Quaritch", "credit_id": "52fe48009251416c750ac9cf", "gender": 2, "id": 32747, "name": "Stephen Lang", "order": 3}, {"cast_id": 5, "character": "Trudy Chacon", "credit_id": "52fe48009251416c750ac9d3", "gender": 1, "id": 17647, "name": "Michelle Rodriguez", "order": 4}, {"cast_id": 8, "character": "Selfridge", "credit_id": "52fe48009251416c750ac9e1", "gender": 2, "id": 1771, "name": "Giovanni Ribisi", "order": 5}, {"cast_id": 7, "character": "Norm Spellman", "credit_id": "52fe48009251416c750ac9dd", "gender": 2, "id": 59231, "name": "Joel David Moore", "order": 6}, {"cast_id": 9, "character": "Moat", "credit_id": "52fe48009251416c750ac9e5", "gender": 1, "id": 30485, "name": "CCH Pounder", "order": 7}, {"cast_id": 11, "character": "Eytukan", "credit_id": "52fe48009251416c750ac9ed", "gender": 2, "id": 15853, "name": "Wes Studi", "order": 8}, {"cast_id": 10, "character": "Tsu\'Tey", "credit_id": "52fe48009251416c750ac9e9", "gender": 2, "id": 10964, "name": "Laz Alonso", "order": 9}, {"cast_id": 12, "character": "Dr. Max Patel", "credit_id": "52fe48009251416c750ac9f1", "gender": 2, "id": 95697, "name": "Dileep Rao", "order": 10}, {"cast_id": 13, "character": "Lyle Wainfleet", "credit_id": "52fe48009251416c750ac9f5", "gender": 2, "id": 98215, "name": "Matt Gerald", "order": 11}, {"cast_id": 32, "character": "Private Fike", "credit_id": "52fe48009251416c750aca5b", "gender": 2, "id": 154153, "name": "Sean Anthony Moran", "order": 12}, {"cast_id": 33, "character": "Cryo Vault Med Tech", "credit_id": "52fe48009251416c750aca5f", "gender": 2, "id": 397312, "name": "Jason Whyte", "order": 13}, {"cast_id": 34, "character": "Venture Star Crew Chief", "credit_id": "52fe48009251416c750aca63", "gender": 2, "id": 42317, "name": "Scott Lawrence", "order": 14}, {"cast_id": 35, "character": "Lock Up Trooper", "credit_id": "52fe48009251416c750aca67", "gender": 2, "id": 986734, "name": "Kelly Kilgour", "order": 15}, {"cast_id": 36, "character": "Shuttle Pilot", "credit_id": "52fe48009251416c750aca6b", "gender": 0, "id": 1207227, "name": "James Patrick Pitt", "order": 16}, {"cast_id": 37, "character": "Shuttle Co-Pilot", "credit_id": "52fe48009251416c750aca6f", "gender": 0, "id": 1180936, "name": "Sean Patrick Murphy", "order": 17}, {"cast_id": 38, "character": "Shuttle Crew Chief", "credit_id": "52fe48009251416c750aca73", "gender": 2, "id": 1019578, "name": "Peter Dillon", "order": 18}, {"cast_id": 39, "character": "Tractor Operator / Troupe", "credit_id": "52fe48009251416c750aca77", "gender": 0, "id": 91443, "name": "Kevin Dorman", "order": 19}, {"cast_id": 40, "character": "Dragon Gunship Pilot", "credit_id": "52fe48009251416c750aca7b", "gender": 2, "id": 173391, "name": "Kelson Henderson", "order": 20}, {"cast_id": 41, "character": "Dragon Gunship Gunner", "credit_id": "52fe48009251416c750aca7f", "gender": 0, "id": 1207236, "name": "David Van Horn", "order": 21}, {"cast_id": 42, "character": "Dragon Gunship Navigator", "credit_id": "52fe48009251416c750aca83", "gender": 0, "id": 215913, "name": "Jacob Tomuri", "order": 22}, {"cast_id": 43, "character": "Suit #1", "credit_id": "52fe48009251416c750aca87", "gender": 0, "id": 143206, "name": "Michael Blain-Rozgay", "order": 23}, {"cast_id": 44, "character": "Suit #2", "credit_id": "52fe48009251416c750aca8b", "gender": 2, "id": 169676, "name": "Jon Curry", "order": 24}, {"cast_id": 46, "character": "Ambient Room Tech", "credit_id": "52fe48009251416c750aca8f", "gender": 0, "id": 1048610, "name": "Luke Hawker", "order": 25}, {"cast_id": 47, "character": "Ambient Room Tech / Troupe", "credit_id": "52fe48009251416c750aca93", "gender": 0, "id": 42288, "name": "Woody Schultz", "order": 26}, {"cast_id": 48, "character": "Horse Clan Leader", "credit_id": "52fe48009251416c750aca97", "gender": 2, "id": 68278, "name": "Peter Mensah", "order": 27}, {"cast_id": 49, "character": "Link Room Tech", "credit_id": "52fe48009251416c750aca9b", "gender": 0, "id": 1207247, "name": "Sonia Yee", "order": 28}, {"cast_id": 50, "character": "Basketball Avatar / Troupe", "credit_id": "52fe48009251416c750aca9f", "gender": 1, "id": 1207248, "name": "Jahnel Curfman", "order": 29}, {"cast_id": 51, "character": "Basketball Avatar", "credit_id": "52fe48009251416c750acaa3", "gender": 0, "id": 89714, "name": "Ilram Choi", "order": 30}, {"cast_id": 52, "character": "Na\'vi Child", "credit_id": "52fe48009251416c750acaa7", "gender": 0, "id": 1207249, "name": "Kyla Warren", "order": 31}, {"cast_id": 53, "character": "Troupe", "credit_id": "52fe48009251416c750acaab", "gender": 0, "id": 1207250, "name": "Lisa Roumain", "order": 32}, {"cast_id": 54, "character": "Troupe", "credit_id": "52fe48009251416c750acaaf", "gender": 1, "id": 83105, "name": "Debra Wilson", "order": 33}, {"cast_id": 57, "character": "Troupe", "credit_id": "52fe48009251416c750acabb", "gender": 0, "id": 1207253, "name": "Chris Mala", "order": 34}, {"cast_id": 55, "character": "Troupe", "credit_id": "52fe48009251416c750acab3", "gender": 0, "id": 1207251, "name": "Taylor Kibby", "order": 35}, {"cast_id": 56, "character": "Troupe", "credit_id": "52fe48009251416c750acab7", "gender": 0, "id": 1207252, "name": "Jodie Landau", "order": 36}, {"cast_id": 58, "character": "Troupe", "credit_id": "52fe48009251416c750acabf", "gender": 0, "id": 1207254, "name": "Julie Lamm", "order": 37}, {"cast_id": 59, "character": "Troupe", "credit_id": "52fe48009251416c750acac3", "gender": 0, "id": 1207257, "name": "Cullen B. Madden", "order": 38}, {"cast_id": 60, "character": "Troupe", "credit_id": "52fe48009251416c750acac7", "gender": 0, "id": 1207259, "name": "Joseph Brady Madden", "order": 39}, {"cast_id": 61, "character": "Troupe", "credit_id": "52fe48009251416c750acacb", "gender": 0, "id": 1207262, "name": "Frankie Torres", "order": 40}, {"cast_id": 62, "character": "Troupe", "credit_id": "52fe48009251416c750acacf", "gender": 1, "id": 1158600, "name": "Austin Wilson", "order": 41}, {"cast_id": 63, "character": "Troupe", "credit_id": "52fe48019251416c750acad3", "gender": 1, "id": 983705, "name": "Sara Wilson", "order": 42}, {"cast_id": 64, "character": "Troupe", "credit_id": "52fe48019251416c750acad7", "gender": 0, "id": 1207263, "name": "Tamica Washington-Miller", "order": 43}, {"cast_id": 65, "character": "Op Center Staff", "credit_id": "52fe48019251416c750acadb", "gender": 1, "id": 1145098, "name": "Lucy Briant", "order": 44}, {"cast_id": 66, "character": "Op Center Staff", "credit_id": "52fe48019251416c750acadf", "gender": 2, "id": 33305, "name": "Nathan Meister", "order": 45}, {"cast_id": 67, "character": "Op Center Staff", "credit_id": "52fe48019251416c750acae3", "gender": 0, "id": 1207264, "name": "Gerry Blair", "order": 46}, {"cast_id": 68, "character": "Op Center Staff", "credit_id": "52fe48019251416c750acae7", "gender": 2, "id": 33311, "name": "Matthew Chamberlain", "order": 47}, {"cast_id": 69, "character": "Op Center Staff", "credit_id": "52fe48019251416c750acaeb", "gender": 0, "id": 1207265, "name": "Paul Yates", "order": 48}, {"cast_id": 70, "character": "Op Center Duty Officer", "credit_id": "52fe48019251416c750acaef", "gender": 0, "id": 1207266, "name": "Wray Wilson", "order": 49}, {"cast_id": 71, "character": "Op Center Staff", "credit_id": "52fe48019251416c750acaf3", "gender": 2, "id": 54492, "name": "James Gaylyn", "order": 50}, {"cast_id": 72, "character": "Dancer", "credit_id": "52fe48019251416c750acaf7", "gender": 0, "id": 1207267, "name": "Melvin Leno Clark III", "order": 51}, {"cast_id": 73, "character": "Dancer", "credit_id": "52fe48019251416c750acafb", "gender": 0, "id": 1207268, "name": "Carvon Futrell", "order": 52}, {"cast_id": 74, "character": "Dancer", "credit_id": "52fe48019251416c750acaff", "gender": 0, "id": 1207269, "name": "Brandon Jelkes", "order": 53}, {"cast_id": 75, "character": "Dancer", "credit_id": "52fe48019251416c750acb03", "gender": 0, "id": 1207270, "name": "Micah Moch", "order": 54}, {"cast_id": 76, "character": "Dancer", "credit_id": "52fe48019251416c750acb07", "gender": 0, "id": 1207271, "name": "Hanniyah Muhammad", "order": 55}, {"cast_id": 77, "character": "Dancer", "credit_id": "52fe48019251416c750acb0b", "gender": 0, "id": 1207272, "name": "Christopher Nolen", "order": 56}, {"cast_id": 78, "character": "Dancer", "credit_id": "52fe48019251416c750acb0f", "gender": 0, "id": 1207273, "name": "Christa Oliver", "order": 57}, {"cast_id": 79, "character": "Dancer", "credit_id": "52fe48019251416c750acb13", "gender": 0, "id": 1207274, "name": "April Marie Thomas", "order": 58}, {"cast_id": 80, "character": "Dancer", "credit_id": "52fe48019251416c750acb17", "gender": 0, "id": 1207275, "name": "Bravita A. Threatt", "order": 59}, {"cast_id": 81, "character": "Mining Chief (uncredited)", "credit_id": "52fe48019251416c750acb1b", "gender": 0, "id": 1207276, "name": "Colin Bleasdale", "order": 60}, {"cast_id": 82, "character": "Veteran Miner (uncredited)", "credit_id": "52fe48019251416c750acb1f", "gender": 0, "id": 107969, "name": "Mike Bodnar", "order": 61}, {"cast_id": 83, "character": "Richard (uncredited)", "credit_id": "52fe48019251416c750acb23", "gender": 0, "id": 1207278, "name": "Matt Clayton", "order": 62}, {"cast_id": 84, "character": "Nav\'i (uncredited)", "credit_id": "52fe48019251416c750acb27", "gender": 1, "id": 147898, "name": "Nicole Dionne", "order": 63}, {"cast_id": 85, "character": "Trooper (uncredited)", "credit_id": "52fe48019251416c750acb2b", "gender": 0, "id": 1207280, "name": "Jamie Harrison", "order": 64}, {"cast_id": 86, "character": "Trooper (uncredited)", "credit_id": "52fe48019251416c750acb2f", "gender": 0, "id": 1207281, "name": "Allan Henry", "order": 65}, {"cast_id": 87, "character": "Ground Technician (uncredited)", "credit_id": "52fe48019251416c750acb33", "gender": 2, "id": 1207282, "name": "Anthony Ingruber", "order": 66}, {"cast_id": 88, "character": "Flight Crew Mechanic (uncredited)", "credit_id": "52fe48019251416c750acb37", "gender": 0, "id": 1207283, "name": "Ashley Jeffery", "order": 67}, {"cast_id": 14, "character": "Samson Pilot", "credit_id": "52fe48009251416c750ac9f9", "gender": 0, "id": 98216, "name": "Dean Knowsley", "order": 68}, {"cast_id": 89, "character": "Trooper (uncredited)", "credit_id": "52fe48019251416c750acb3b", "gender": 0, "id": 1201399, "name": "Joseph Mika-Hunt", "order": 69}, {"cast_id": 90, "character": "Banshee (uncredited)", "credit_id": "52fe48019251416c750acb3f", "gender": 0, "id": 236696, "name": "Terry Notary", "order": 70}, {"cast_id": 91, "character": "Soldier (uncredited)", "credit_id": "52fe48019251416c750acb43", "gender": 0, "id": 1207287, "name": "Kai Pantano", "order": 71}, {"cast_id": 92, "character": "Blast Technician (uncredited)", "credit_id": "52fe48019251416c750acb47", "gender": 0, "id": 1207288, "name": "Logan Pithyou", "order": 72}, {"cast_id": 93, "character": "Vindum Raah (uncredited)", "credit_id": "52fe48019251416c750acb4b", "gender": 0, "id": 1207289, "name": "Stuart Pollock", "order": 73}, {"cast_id": 94, "character": "Hero (uncredited)", "credit_id": "52fe48019251416c750acb4f", "gender": 0, "id": 584868, "name": "Raja", "order": 74}, {"cast_id": 95, "character": "Ops Centreworker (uncredited)", "credit_id": "52fe48019251416c750acb53", "gender": 0, "id": 1207290, "name": "Gareth Ruck", "order": 75}, {"cast_id": 96, "character": "Engineer (uncredited)", "credit_id": "52fe48019251416c750acb57", "gender": 0, "id": 1062463, "name": "Rhian Sheehan", "order": 76}, {"cast_id": 97, "character": "Col. Quaritch\'s Mech Suit (uncredited)", "credit_id": "52fe48019251416c750acb5b", "gender": 0, "id": 60656, "name": "T. J. Storm", "order": 77}, {"cast_id": 98, "character": "Female Marine (uncredited)", "credit_id": "52fe48019251416c750acb5f", "gender": 0, "id": 1207291, "name": "Jodie Taylor", "order": 78}, {"cast_id": 99, "character": "Ikran Clan Leader (uncredited)", "credit_id": "52fe48019251416c750acb63", "gender": 1, "id": 1186027, "name": "Alicia Vela-Bailey", "order": 79}, {"cast_id": 100, "character": "Geologist (uncredited)", "credit_id": "52fe48019251416c750acb67", "gender": 0, "id": 1207292, "name": "Richard Whiteside", "order": 80}, {"cast_id": 101, "character": "Na\'vi (uncredited)", "credit_id": "52fe48019251416c750acb6b", "gender": 0, "id": 103259, "name": "Nikie Zambo", "order": 81}, {"cast_id": 102, "character": "Ambient Room Tech / Troupe", "credit_id": "52fe48019251416c750acb6f", "gender": 1, "id": 42286, "name": "Julene Renee", "order": 82}]'],
      dtype=object)

In [7]:
movies=movies.merge(credit,on="title")
movies.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 4809 entries, 0 to 4808
Data columns (total 23 columns):
 #   Column                Non-Null Count  Dtype
---  ------                --------------  -----
 0   budget                4809 non-null   int64
 1   genres                4809 non-null   object
 2   homepage              1713 non-null   object
 3   id                    4809 non-null   int64
 4   keywords              4809 non-null   object
 5   original_language     4809 non-null   object
 6   original_title        4809 non-null   object
 7   overview              4806 non-null   object
 8   popularity            4809 non-null   float64
 9   production_companies  4809 non-null   object
 10  production_countries  4809 non-null   object
 11  release_date          4808 non-null   object
 12  revenue               4809 non-null   int64
 13  runtime               4807 non-null   float64
 14  spoken_languages      4809 non-null   object
 15  status                4809 non-null   object
 16  tagline               3965 non-null   object
 17  title                 4809 non-null   object
 18  vote_average          4809 non-null   float64
 19  vote_count            4809 non-null   int64
 20  movie_id              4809 non-null   int64
 21  cast                  4809 non-null   object
 22  crew                  4809 non-null   object
dtypes: float64(3), int64(5), object(15)
memory usage: 864.2+ KB

In [8]:
movies=movies[["id","title","overview","genres","keywords","cast","crew"]]

movies.head()

,id,title,overview,genres,keywords,cast,crew
0,19995,Avatar,"In the 22nd century, a paraplegic Marine is di...","[{""id"": 28, ""name"": ""Action""}, {""id"": 12, ""nam...","[{""id"": 1463, ""name"": ""culture clash""}, {""id"":...","[{""cast_id"": 242, ""character"": ""Jake Sully"", ""...","[{""credit_id"": ""52fe48009251416c750aca23"", ""de..."
1,285,Pirates of the Caribbean: At World's End,"Captain Barbossa, long believed to be dead, ha...","[{""id"": 12, ""name"": ""Adventure""}, {""id"": 14, ""...","[{""id"": 270, ""name"": ""ocean""}, {""id"": 726, ""na...","[{""cast_id"": 4, ""character"": ""Captain Jack Spa...","[{""credit_id"": ""52fe4232c3a36847f800b579"", ""de..."
2,206647,Spectre,A cryptic message from Bond’s past sends him o...,"[{""id"": 28, ""name"": ""Action""}, {""id"": 12, ""nam...","[{""id"": 470, ""name"": ""spy""}, {""id"": 818, ""name...","[{""cast_id"": 1, ""character"": ""James Bond"", ""cr...","[{""credit_id"": ""54805967c3a36829b5002c41"", ""de..."
3,49026,The Dark Knight Rises,Following the death of District Attorney Harve...,"[{""id"": 28, ""name"": ""Action""}, {""id"": 80, ""nam...","[{""id"": 849, ""name"": ""dc comics""}, {""id"": 853,...","[{""cast_id"": 2, ""character"": ""Bruce Wayne / Ba...","[{""credit_id"": ""52fe4781c3a36847f81398c3"", ""de..."
4,49529,John Carter,"John Carter is a war-weary, former military ca...","[{""id"": 28, ""name"": ""Action""}, {""id"": 12, ""nam...","[{""id"": 818, ""name"": ""based on novel""}, {""id"":...","[{""cast_id"": 5, ""character"": ""John Carter"", ""c...","[{""credit_id"": ""52fe479ac3a36847f813eaa3"", ""de..."

In [9]:
#finding missing values
movies.isnull().sum()

id          0
title       0
overview    3
genres      0
keywords    0
cast        0
crew        0
dtype: int64

overview has 3 missing values so we drop then becoz the missing nubers are low

In [10]:
movies.dropna(inplace=True)

In [11]:
#checkign duplicates 
movies.duplicated().sum()

np.int64(0)

In [12]:
import ast

In [13]:
def convert(obj):
    l=[]
    for i in ast.literal_eval(obj):
        l.append(i["name"])

    return l

In [14]:
movies["genres"]=movies["genres"].apply(convert)

In [15]:
movies["keywords"]=movies["keywords"].apply(convert)

In [16]:
def convert3(obj):
    l=[]
    counter=0
    for i in ast.literal_eval(obj):
        
        if counter!=3:
            l.append(i["name"])
            counter+=1
        else:
            break

 
    return l

In [17]:
movies["cast"]=movies["cast"].apply(convert3)

In [18]:
def fetch_director(obj):
    l=[]
    for i in ast.literal_eval(obj):
     if i["job"]=="Director": 
        l.append(i["name"])
        break

    return l

In [19]:
movies["crew"]=movies["crew"].apply(fetch_director)

In [20]:
movies["overview"][0]
movies["overview"]=movies["overview"].apply(lambda x:x.split())

In [21]:
movies.head()

,id,title,overview,genres,keywords,cast,crew
0,19995,Avatar,"[In, the, 22nd, century,, a, paraplegic, Marin...","[Action, Adventure, Fantasy, Science Fiction]","[culture clash, future, space war, space colon...","[Sam Worthington, Zoe Saldana, Sigourney Weaver]",[James Cameron]
1,285,Pirates of the Caribbean: At World's End,"[Captain, Barbossa,, long, believed, to, be, d...","[Adventure, Fantasy, Action]","[ocean, drug abuse, exotic island, east india ...","[Johnny Depp, Orlando Bloom, Keira Knightley]",[Gore Verbinski]
2,206647,Spectre,"[A, cryptic, message, from, Bond’s, past, send...","[Action, Adventure, Crime]","[spy, based on novel, secret agent, sequel, mi...","[Daniel Craig, Christoph Waltz, Léa Seydoux]",[Sam Mendes]
3,49026,The Dark Knight Rises,"[Following, the, death, of, District, Attorney...","[Action, Crime, Drama, Thriller]","[dc comics, crime fighter, terrorist, secret i...","[Christian Bale, Michael Caine, Gary Oldman]",[Christopher Nolan]
4,49529,John Carter,"[John, Carter, is, a, war-weary,, former, mili...","[Action, Adventure, Science Fiction]","[based on novel, mars, medallion, space travel...","[Taylor Kitsch, Lynn Collins, Samantha Morton]",[Andrew Stanton]

In [22]:
#replacing spaces between the genres keywords cast and crew
#science friction --> sciencefriction 

movies["genres"]=movies["genres"].apply(lambda x:[i.replace(" ","") for i in x])
movies["keywords"]=movies["keywords"].apply(lambda x:[i.replace(" ","") for i in x])
movies["cast"]=movies["cast"].apply(lambda x:[i.replace(" ","") for i in x])
movies["crew"]=movies["crew"].apply(lambda x:[i.replace(" ","") for i in x])

In [23]:
#make a new column combined with the five columns
movies['combined_column'] = movies['overview'] + movies['genres'] + movies['cast'] + movies['keywords'] + movies['crew']

In [24]:
#making a neew data frame of three columns title , id and combined column
new_df=movies[["id","title","combined_column"]]
new_df.head()

,id,title,combined_column
0,19995,Avatar,"[In, the, 22nd, century,, a, paraplegic, Marin..."
1,285,Pirates of the Caribbean: At World's End,"[Captain, Barbossa,, long, believed, to, be, d..."
2,206647,Spectre,"[A, cryptic, message, from, Bond’s, past, send..."
3,49026,The Dark Knight Rises,"[Following, the, death, of, District, Attorney..."
4,49529,John Carter,"[John, Carter, is, a, war-weary,, former, mili..."

In [25]:
new_df["combined_column"][0]

['In',
 'the',
 '22nd',
 'century,',
 'a',
 'paraplegic',
 'Marine',
 'is',
 'dispatched',
 'to',
 'the',
 'moon',
 'Pandora',
 'on',
 'a',
 'unique',
 'mission,',
 'but',
 'becomes',
 'torn',
 'between',
 'following',
 'orders',
 'and',
 'protecting',
 'an',
 'alien',
 'civilization.',
 'Action',
 'Adventure',
 'Fantasy',
 'ScienceFiction',
 'SamWorthington',
 'ZoeSaldana',
 'SigourneyWeaver',
 'cultureclash',
 'future',
 'spacewar',
 'spacecolony',
 'society',
 'spacetravel',
 'futuristic',
 'romance',
 'space',
 'alien',
 'tribe',
 'alienplanet',
 'cgi',
 'marine',
 'soldier',
 'battle',
 'loveaffair',
 'antiwar',
 'powerrelations',
 'mindandsoul',
 '3d',
 'JamesCameron']

In [26]:
#making combined column a string 
new_df["combined_column"]=new_df["combined_column"].apply(lambda x:" ".join(x))
new_df.head()

C:\Users\LENOVO\AppData\Local\Temp\ipykernel_11460\1567267115.py:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  new_df["combined_column"]=new_df["combined_column"].apply(lambda x:" ".join(x))

,id,title,combined_column
0,19995,Avatar,"In the 22nd century, a paraplegic Marine is di..."
1,285,Pirates of the Caribbean: At World's End,"Captain Barbossa, long believed to be dead, ha..."
2,206647,Spectre,A cryptic message from Bond’s past sends him o...
3,49026,The Dark Knight Rises,Following the death of District Attorney Harve...
4,49529,John Carter,"John Carter is a war-weary, former military ca..."

In [27]:
# cjonverting to lower case 
new_df["combined_column"]=new_df["combined_column"].apply(lambda x:x.lower())

C:\Users\LENOVO\AppData\Local\Temp\ipykernel_11460\2349909280.py:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  new_df["combined_column"]=new_df["combined_column"].apply(lambda x:x.lower())

In [28]:
#importing the nlp library
from nltk.stem.porter import PorterStemmer

In [29]:
ps=PorterStemmer()

def stem(itme):
    y=[]
    for i in itme.split():
        y.append(ps.stem(i))
    return " ".join(y)

In [30]:
new_df["combined_column"]=new_df["combined_column"].apply(stem)

C:\Users\LENOVO\AppData\Local\Temp\ipykernel_11460\2939424395.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  new_df["combined_column"]=new_df["combined_column"].apply(stem)

In [31]:
new_df.head()

,id,title,combined_column
0,19995,Avatar,"in the 22nd century, a parapleg marin is dispa..."
1,285,Pirates of the Caribbean: At World's End,"captain barbossa, long believ to be dead, ha c..."
2,206647,Spectre,a cryptic messag from bond’ past send him on a...
3,49026,The Dark Knight Rises,follow the death of district attorney harvey d...
4,49529,John Carter,"john carter is a war-weary, former militari ca..."

In [32]:
#vectorization of the combined comumn

In [33]:
from sklearn.feature_extraction.text import CountVectorizer

In [34]:
#pickingthe most occuring words in the combined_column

cv=CountVectorizer(max_features=5000,stop_words="english")

vector=cv.fit_transform(new_df['combined_column']).toarray()

In [35]:
# this are the words selected by the countvectorizer from the making vectors 
cv.get_feature_names_out()

array(['000', '007', '10', ..., 'zone', 'zoo', 'zooeydeschanel'],
      shape=(5000,), dtype=object)

In [36]:
#the  5 movie with the most accour words 
vector[5]

array([0, 0, 0, ..., 0, 0, 0], shape=(5000,))

Cosine Distance Overview
Cosine similarity measures the cosine of the angle between two vectors in a multidimensional space. It ranges from -1 to 1:
1: Vectors are identical.
0: Vectors are orthogonal (completely different directions).
-1: Vectors are diametrically opposite.
Cosine distance is the complement of similarity:

Cosine Distance=1−Cosine Similarity
from sklearn.metrics.pairwise import cosine_similarity

# Define two vectors
vector1 = [1, 2, 3]
vector2 = [4, 5, 6]

# Calculate cosine similarity
similarity = cosine_similarity([vector1], [vector2])

# Calculate cosine distance
distance = 1 - similarity

print("Cosine Similarity:", similarity[0][0])
print("Cosine Distance:", distance[0][0])

In [37]:
from sklearn.metrics.pairwise import cosine_similarity

similarity=cosine_similarity(vector)

In [38]:
sorted(list(enumerate(similarity[0])),reverse=True,key =lambda x:x[1])

[(0, np.float64(1.0000000000000002)),
 (1214, np.float64(0.28676966733820225)),
 (2405, np.float64(0.26901379342448517)),
 (3728, np.float64(0.2605130246476754)),
 (507, np.float64(0.255608593705383)),
 (539, np.float64(0.25038669783359574)),
 (582, np.float64(0.24511108480187255)),
 (1202, np.float64(0.24455799402225925)),
 (1192, np.float64(0.2367785320221084)),
 (61, np.float64(0.23179316248638276)),
 (778, np.float64(0.23174488732966073)),
 (4046, np.float64(0.2278389747471728)),
 (1916, np.float64(0.2252817784447915)),
 (2782, np.float64(0.21853668936906193)),
 (172, np.float64(0.21239769762143662)),
 (972, np.float64(0.2108663315950723)),
 (322, np.float64(0.2105263157894737)),
 (2329, np.float64(0.20443988269091456)),
 (3606, np.float64(0.20437977982832192)),
 (260, np.float64(0.20395079136182276)),
 (151, np.float64(0.2029530274475215)),
 (4190, np.float64(0.2029530274475215)),
 (1440, np.float64(0.20277677641345318)),
 (74, np.float64(0.2024645717996314)),
 (1087, np.float64(0.2020475485519274)),
 (3671, np.float64(0.1979082783981174)),
 (973, np.float64(0.19767387315371682)),
 (577, np.float64(0.1976738731537168)),
 (47, np.float64(0.19672236884115843)),
 (2969, np.float64(0.1925214071641298)),
 (942, np.float64(0.19134594929397597)),
 (495, np.float64(0.19088542889273336)),
 (1199, np.float64(0.19088542889273336)),
 (305, np.float64(0.19007487139298027)),
 (4, np.float64(0.1892994097121204)),
 (4405, np.float64(0.18731716231633883)),
 (94, np.float64(0.1873171623163388)),
 (27, np.float64(0.18693292157876878)),
 (3325, np.float64(0.1860807318911967)),
 (1273, np.float64(0.18394180184548975)),
 (1327, np.float64(0.18394180184548975)),
 (2997, np.float64(0.1813690625275029)),
 (3997, np.float64(0.18074256993863339)),
 (83, np.float64(0.17996850826633903)),
 (1069, np.float64(0.17954621161490197)),
 (220, np.float64(0.1777046633277277)),
 (1319, np.float64(0.17699808135119718)),
 (168, np.float64(0.17521916101261562)),
 (184, np.float64(0.17521916101261562)),
 (2200, np.float64(0.17521916101261562)),
 (4336, np.float64(0.17521916101261562)),
 (931, np.float64(0.1748149640244195)),
 (373, np.float64(0.17292861596651865)),
 (300, np.float64(0.1711905958155815)),
 (3536, np.float64(0.1711905958155815)),
 (36, np.float64(0.17119059581558146)),
 (3160, np.float64(0.17040572913692198)),
 (1978, np.float64(0.16943474841747155)),
 (529, np.float64(0.16742770563222897)),
 (1827, np.float64(0.16742770563222897)),
 (91, np.float64(0.16692446522239718)),
 (661, np.float64(0.1661625969589056)),
 (41, np.float64(0.16563698349810535)),
 (67, np.float64(0.16452254913212452)),
 (150, np.float64(0.16426202236672155)),
 (1533, np.float64(0.16222142113076254)),
 (2511, np.float64(0.16222142113076254)),
 (342, np.float64(0.16122923187750418)),
 (595, np.float64(0.16059101370939324)),
 (31, np.float64(0.15907119074394446)),
 (1176, np.float64(0.15789473684210528)),
 (4008, np.float64(0.15737789507292674)),
 (2727, np.float64(0.15609763526361567)),
 (149, np.float64(0.15511334686589626)),
 (838, np.float64(0.1540171257313038)),
 (26, np.float64(0.15389675281277312)),
 (187, np.float64(0.15389675281277312)),
 (1379, np.float64(0.152008377581442)),
 (111, np.float64(0.15018785229652767)),
 (1342, np.float64(0.15018785229652767)),
 (311, np.float64(0.15018785229652765)),
 (513, np.float64(0.14843120879858804)),
 (2071, np.float64(0.14808721943977307)),
 (7, np.float64(0.14673479641335554)),
 (52, np.float64(0.14673479641335554)),
 (2756, np.float64(0.14659886790209342)),
 (127, np.float64(0.14601068654819693)),
 (579, np.float64(0.14567913668701626)),
 (581, np.float64(0.14567913668701626)),
 (108, np.float64(0.14509525002200235)),
 (1295, np.float64(0.14509525002200235)),
 (466, np.float64(0.14509525002200233)),
 (1392, np.float64(0.14421498760030763)),
 (1475, np.float64(0.1442149876003076)),
 (1353, np.float64(0.14350946197048198)),
 (1934, np.float64(0.14350946197048198)),
 (275, np.float64(0.1433848336691011)),
 (294, np.float64(0.1433848336691011)),
 (3352, np.float64(0.1433848336691011)),
 (1054, np.float64(0.1419745572840903)),
 (1271, np.float64(0.1419745572840903)),
 (490, np.float64(0.14159846508095775)),
 (1484, np.float64(0.14159846508095775)),
 (413, np.float64(0.1411956236812263)),
 (461, np.float64(0.1411956236812263)),
 (568, np.float64(0.1411956236812263)),
 (2492, np.float64(0.1411956236812263)),
 (95, np.float64(0.14048787173725413)),
 (17, np.float64(0.13977653617040256)),
 (46, np.float64(0.1391037210186643)),
 (3407, np.float64(0.1391037210186643)),
 (1961, np.float64(0.13872950617564817)),
 (56, np.float64(0.13834289277321493)),
 (249, np.float64(0.13834289277321493)),
 (1325, np.float64(0.13834289277321493)),
 (3779, np.float64(0.13834289277321493)),
 (72, np.float64(0.13710212427677043)),
 (859, np.float64(0.13710212427677043)),
 (2165, np.float64(0.13710212427677043)),
 (4538, np.float64(0.13629325512727639)),
 (476, np.float64(0.13530201829834768)),
 (505, np.float64(0.13530201829834768)),
 (668, np.float64(0.13530201829834768)),
 (935, np.float64(0.13530201829834768)),
 (3980, np.float64(0.13530201829834768)),
 (843, np.float64(0.13518451760896877)),
 (1804, np.float64(0.13518451760896877)),
 (4348, np.float64(0.13497638119975428)),
 (1320, np.float64(0.13476498501489081)),
 (158, np.float64(0.13369695534647594)),
 (502, np.float64(0.13369695534647594)),
 (777, np.float64(0.13369695534647594)),
 (126, np.float64(0.13334518676566626)),
 (1556, np.float64(0.13334518676566626)),
 (1369, np.float64(0.1324532357065044)),
 (2374, np.float64(0.1324532357065044)),
 (2580, np.float64(0.1324532357065044)),
 (589, np.float64(0.13245323570650439)),
 (4077, np.float64(0.13157894736842107)),
 (2129, np.float64(0.13124359177794215)),
 (14, np.float64(0.12988108336653278)),
 (1013, np.float64(0.12988108336653278)),
 (2177, np.float64(0.12988108336653278)),
 (3620, np.float64(0.12988108336653278)),
 (134, np.float64(0.12977713690461004)),
 (368, np.float64(0.12977713690461004)),
 (1770, np.float64(0.12977713690461004)),
 (2869, np.float64(0.12892051277806202)),
 (138, np.float64(0.12824729401064427)),
 (1084, np.float64(0.12824729401064427)),
 (2682, np.float64(0.12824729401064427)),
 (4228, np.float64(0.12824729401064427)),
 (487, np.float64(0.12725695259515557)),
 (773, np.float64(0.12725695259515557)),
 (2968, np.float64(0.12725695259515557)),
 (369, np.float64(0.126673647984535)),
 (937, np.float64(0.126673647984535)),
 (2476, np.float64(0.12565617248750865)),
 (1737, np.float64(0.12565617248750863)),
 (166, np.float64(0.12515654358043973)),
 (754, np.float64(0.12515654358043973)),
 (2446, np.float64(0.12515654358043973)),
 (3626, np.float64(0.12515654358043973)),
 (483, np.float64(0.12487810821089254)),
 (1094, np.float64(0.12487810821089254)),
 (1156, np.float64(0.12487810821089254)),
 (102, np.float64(0.12462194771917919)),
 (84, np.float64(0.12361284651454937)),
 (208, np.float64(0.12262786789699316)),
 (2648, np.float64(0.12262786789699316)),
 (3374, np.float64(0.12262786789699316)),
 (1874, np.float64(0.12262786789699313)),
 (438, np.float64(0.12227899701112963)),
 (557, np.float64(0.12227899701112963)),
 (1297, np.float64(0.12227899701112963)),
 (2327, np.float64(0.12166606584807191)),
 (2670, np.float64(0.12166606584807191)),
 (3081, np.float64(0.12166606584807191)),
 (3998, np.float64(0.12166606584807191)),
 (139, np.float64(0.12072654548783007)),
 (68, np.float64(0.1204950466257556)),
 (781, np.float64(0.1204950466257556)),
 (1002, np.float64(0.1204950466257556)),
 (1272, np.float64(0.1204950466257556)),
 (1654, np.float64(0.1204950466257556)),
 (2737, np.float64(0.1204950466257556)),
 (1000, np.float64(0.11980845957463077)),
 (549, np.float64(0.11959121830873498)),
 (870, np.float64(0.11959121830873498)),
 (900, np.float64(0.11959121830873498)),
 (3233, np.float64(0.11959121830873498)),
 (1045, np.float64(0.11846977555181847)),
 (1829, np.float64(0.11846977555181847)),
 (2056, np.float64(0.11846977555181847)),
 (4673, np.float64(0.11846977555181847)),
 (3719, np.float64(0.11803342130469506)),
 (1669, np.float64(0.11803342130469505)),
 (1711, np.float64(0.11803342130469505)),
 (2785, np.float64(0.11803342130469505)),
 (160, np.float64(0.11712303424679457)),
 (182, np.float64(0.11707322644771176)),
 (278, np.float64(0.11707322644771176)),
 (1613, np.float64(0.11707322644771176)),
 (2280, np.float64(0.11707322644771176)),
 (28, np.float64(0.116543309349613)),
 (122, np.float64(0.116543309349613)),
 (422, np.float64(0.116543309349613)),
 (678, np.float64(0.116543309349613)),
 (454, np.float64(0.11587244366483038)),
 (2543, np.float64(0.11587244366483038)),
 (1493, np.float64(0.11551284429847784)),
 (3210, np.float64(0.11506355109724453)),
 (189, np.float64(0.1147078669352809)),
 (1218, np.float64(0.1147078669352809)),
 (236, np.float64(0.11470786693528087)),
 (1299, np.float64(0.11470786693528087)),
 (85, np.float64(0.1141270638770543)),
 (432, np.float64(0.11357771260606365)),
 (1414, np.float64(0.11357771260606365)),
 (889, np.float64(0.11299144295167773)),
 (50, np.float64(0.11295649894498103)),
 (1612, np.float64(0.11295649894498103)),
 (123, np.float64(0.1124803176664619)),
 (420, np.float64(0.1124803176664619)),
 (536, np.float64(0.1124803176664619)),
 (3145, np.float64(0.11239029738980327)),
 (256, np.float64(0.11164843913471803)),
 (808, np.float64(0.11164843913471803)),
 (1346, np.float64(0.11164843913471803)),
 (1571, np.float64(0.11164843913471803)),
 (2368, np.float64(0.11141412945539662)),
 (3307, np.float64(0.11141412945539662)),
 (1508, np.float64(0.11141412945539661)),
 (87, np.float64(0.11128297681493143)),
 (121, np.float64(0.11128297681493143)),
 (232, np.float64(0.11128297681493143)),
 (4468, np.float64(0.11128297681493143)),
 (206, np.float64(0.11092107999698035)),
 (238, np.float64(0.11092107999698035)),
 (228, np.float64(0.11037769642208699)),
 (81, np.float64(0.11020775375559676)),
 (1570, np.float64(0.11020775375559674)),
 (3426, np.float64(0.10968169942141637)),
 (21, np.float64(0.10968169942141635)),
 (449, np.float64(0.10968169942141635)),
 (1029, np.float64(0.10968169942141635)),
 (1941, np.float64(0.10968169942141635)),
 (3006, np.float64(0.10968169942141635)),
 (692, np.float64(0.10936965981495178)),
 (200, np.float64(0.10882143751650175)),
 (627, np.float64(0.10882143751650175)),
 (653, np.float64(0.10882143751650175)),
 (1520, np.float64(0.10882143751650175)),
 (307, np.float64(0.10876595882948199)),
 (5, np.float64(0.10838874619051501)),
 (740, np.float64(0.10838874619051501)),
 (3091, np.float64(0.10838874619051501)),
 (3628, np.float64(0.10838874619051501)),
 (786, np.float64(0.10814761408717502)),
 (3496, np.float64(0.10814761408717502)),
 (4777, np.float64(0.10814761408717502)),
 (229, np.float64(0.1074861545850028)),
 (939, np.float64(0.1074861545850028)),
 (572, np.float64(0.10743376064838502)),
 (332, np.float64(0.106676149412533)),
 (472, np.float64(0.106676149412533)),
 (687, np.float64(0.106676149412533)),
 (1235, np.float64(0.106676149412533)),
 (170, np.float64(0.10650358071057624)),
 (262, np.float64(0.10650358071057624)),
 (1164, np.float64(0.10619884881071831)),
 (1497, np.float64(0.10619884881071831)),
 (1741, np.float64(0.10619884881071831)),
 (2157, np.float64(0.10619884881071831)),
 (2517, np.float64(0.10619884881071831)),
 (2630, np.float64(0.10619884881071831)),
 (4133, np.float64(0.10619884881071831)),
 (467, np.float64(0.10559715077387793)),
 (541, np.float64(0.10559715077387793)),
 (1492, np.float64(0.10559715077387793)),
 (131, np.float64(0.10526315789473685)),
 (295, np.float64(0.10526315789473685)),
 (814, np.float64(0.10526315789473685)),
 (2068, np.float64(0.10526315789473685)),
 (3338, np.float64(0.10526315789473685)),
 (2494, np.float64(0.10471347707292386)),
 (75, np.float64(0.10390486669322622)),
 (223, np.float64(0.10390486669322622)),
 (1193, np.float64(0.10390486669322622)),
 (1767, np.float64(0.10390486669322622)),
 (2144, np.float64(0.10390486669322622)),
 (2813, np.float64(0.10390486669322622)),
 (654, np.float64(0.10385162309931599)),
 (2435, np.float64(0.10385162309931599)),
 (105, np.float64(0.1037571695799112)),
 (233, np.float64(0.1037571695799112)),
 (2319, np.float64(0.1037571695799112)),
 (2452, np.float64(0.1037571695799112)),
 (3053, np.float64(0.1037571695799112)),
 (3619, np.float64(0.1037571695799112)),
 (3837, np.float64(0.1037571695799112)),
 (1451, np.float64(0.10301070542879115)),
 (10, np.float64(0.10259783520851541)),
 (508, np.float64(0.10259783520851541)),
 (1080, np.float64(0.10259783520851541)),
 (3150, np.float64(0.10259783520851541)),
 (3632, np.float64(0.10259783520851541)),
 (3753, np.float64(0.10259783520851541)),
 (3872, np.float64(0.10259783520851541)),
 (4095, np.float64(0.10259783520851541)),
 (2102, np.float64(0.10218988991416095)),
 (624, np.float64(0.10147651372376076)),
 (2758, np.float64(0.10147651372376076)),
 (3659, np.float64(0.10147651372376076)),
 (3952, np.float64(0.10147651372376076)),
 (3439, np.float64(0.10138838820672659)),
 (1292, np.float64(0.101338918387628)),
 (2243, np.float64(0.10133891838762799)),
 (1401, np.float64(0.10060545457319173)),
 (1435, np.float64(0.10060545457319173)),
 (2095, np.float64(0.10060545457319173)),
 (312, np.float64(0.10012523486435178)),
 (330, np.float64(0.10012523486435178)),
 (643, np.float64(0.10012523486435178)),
 (986, np.float64(0.10012523486435178)),
 (1035, np.float64(0.10012523486435178)),
 (1610, np.float64(0.10012523486435178)),
 (35, np.float64(0.09933992677987831)),
 (157, np.float64(0.09933992677987831)),
 (319, np.float64(0.09933992677987831)),
 (325, np.float64(0.09933992677987831)),
 (715, np.float64(0.09933992677987831)),
 (1075, np.float64(0.09933992677987831)),
 (1278, np.float64(0.09933992677987831)),
 (1880, np.float64(0.09933992677987831)),
 (2049, np.float64(0.09933992677987831)),
 (4016, np.float64(0.09933992677987831)),
 (4196, np.float64(0.09933992677987831)),
 (4490, np.float64(0.09933992677987831)),
 (363, np.float64(0.09909250441117726)),
 (491, np.float64(0.09909250441117726)),
 (266, np.float64(0.0989541391990587)),
 (445, np.float64(0.0989541391990587)),
 (510, np.float64(0.0989541391990587)),
 (898, np.float64(0.0989541391990587)),
 (3618, np.float64(0.0989541391990587)),
 (3781, np.float64(0.0989541391990587)),
 (3933, np.float64(0.0989541391990587)),
 (1771, np.float64(0.09836118442057921)),
 (9, np.float64(0.0978231976089037)),
 (410, np.float64(0.0978231976089037)),
 (480, np.float64(0.0978231976089037)),
 (535, np.float64(0.0978231976089037)),
 (1107, np.float64(0.0978231976089037)),
 (1397, np.float64(0.0978231976089037)),
 (1819, np.float64(0.0978231976089037)),
 (2249, np.float64(0.0978231976089037)),
 (33, np.float64(0.09733285267845754)),
 (148, np.float64(0.09733285267845754)),
 (263, np.float64(0.09733285267845754)),
 (878, np.float64(0.09733285267845754)),
 (1154, np.float64(0.09733285267845754)),
 (1723, np.float64(0.09733285267845754)),
 (1938, np.float64(0.09733285267845754)),
 (2783, np.float64(0.09733285267845754)),
 (4254, np.float64(0.09733285267845754)),
 (4403, np.float64(0.09733285267845754)),
 (4472, np.float64(0.09733285267845754)),
 (334, np.float64(0.0967301666813349)),
 (371, np.float64(0.09567297464698798)),
 (412, np.float64(0.09567297464698798)),
 (2237, np.float64(0.09567297464698798)),
 (2552, np.float64(0.09567297464698798)),
 (4545, np.float64(0.09558988911273408)),
 (362, np.float64(0.09544271444636668)),
 (791, np.float64(0.09544271444636668)),
 (1569, np.float64(0.09544271444636668)),
 (2558, np.float64(0.09544271444636668)),
 (4201, np.float64(0.09544271444636668)),
 (18, np.float64(0.09493290614465533)),
 (11, np.float64(0.09464970485606021)),
 (587, np.float64(0.09464970485606021)),
 (660, np.float64(0.09365858115816941)),
 (920, np.float64(0.09365858115816941)),
 (1274, np.float64(0.09365858115816941)),
 (1355, np.float64(0.09365858115816941)),
 (1470, np.float64(0.09365858115816941)),
 (1682, np.float64(0.09365858115816941)),
 (1688, np.float64(0.09365858115816941)),
 (1717, np.float64(0.09365858115816941)),
 (2392, np.float64(0.09365858115816941)),
 (2484, np.float64(0.09365858115816941)),
 (2588, np.float64(0.09365858115816941)),
 (2641, np.float64(0.09365858115816941)),
 (2646, np.float64(0.09365858115816941)),
 (2816, np.float64(0.09365858115816941)),
 (3535, np.float64(0.09365858115816941)),
 (3718, np.float64(0.09365858115816941)),
 (4331, np.float64(0.09365858115816941)),
 (4502, np.float64(0.09365858115816941)),
 (301, np.float64(0.09365858115816939)),
 (129, np.float64(0.09269795493186431)),
 (243, np.float64(0.09269795493186431)),
 (279, np.float64(0.09269795493186431)),
 (473, np.float64(0.09269795493186431)),
 (596, np.float64(0.09269795493186431)),
 (813, np.float64(0.09269795493186431)),
 (1442, np.float64(0.09269795493186431)),
 (1697, np.float64(0.09269795493186431)),
 (3405, np.float64(0.09269795493186431)),
 (785, np.float64(0.09243423333081695)),
 (219, np.float64(0.09197090092274487)),
 (244, np.float64(0.09197090092274487)),
 (511, np.float64(0.09197090092274487)),
 (978, np.float64(0.09197090092274487)),
 (1752, np.float64(0.09197090092274487)),
 (2089, np.float64(0.09197090092274487)),
 (2647, np.float64(0.09197090092274487)),
 (3734, np.float64(0.09197090092274487)),
 (230, np.float64(0.09183979479633063)),
 (799, np.float64(0.09183979479633063)),
 (239, np.float64(0.09125667909262308)),
 (2566, np.float64(0.09125667909262308)),
 (43, np.float64(0.09086217008485092)),
 (602, np.float64(0.09086217008485092)),
 (995, np.float64(0.09086217008485092)),
 (1231, np.float64(0.09086217008485092)),
 (1842, np.float64(0.09086217008485092)),
 (3879, np.float64(0.09086217008485092)),
 (12, np.float64(0.09037128496931669)),
 (88, np.float64(0.09037128496931669)),
 (167, np.float64(0.09037128496931669)),
 (356, np.float64(0.09037128496931669)),
 (400, np.float64(0.09037128496931669)),
 (1304, np.float64(0.09037128496931669)),
 (1476, np.float64(0.09037128496931669)),
 (2247, np.float64(0.09037128496931669)),
 (2864, np.float64(0.09037128496931669)),
 (2955, np.float64(0.09037128496931669)),
 (331, np.float64(0.08998425413316952)),
 (2359, np.float64(0.08998425413316952)),
 (2792, np.float64(0.08998425413316952)),
 (2852, np.float64(0.08998425413316952)),
 (3387, np.float64(0.08998425413316952)),
 (3441, np.float64(0.08998425413316952)),
 (3460, np.float64(0.08998425413316952)),
 (4343, np.float64(0.08998425413316952)),
 (4353, np.float64(0.08998425413316952)),
 (274, np.float64(0.08977310580745099)),
 (1902, np.float64(0.0891313035643173)),
 (2111, np.float64(0.08903057122447033)),
 (292, np.float64(0.08885233166386385)),
 (564, np.float64(0.08885233166386385)),
 (1025, np.float64(0.08885233166386385)),
 (2656, np.float64(0.08885233166386385)),
 (3320, np.float64(0.08885233166386385)),
 (169, np.float64(0.08830215713766959)),
 (270, np.float64(0.08830215713766959)),
 (618, np.float64(0.08830215713766959)),
 (1779, np.float64(0.08830215713766959)),
 (2105, np.float64(0.08830215713766959)),
 (2709, np.float64(0.08830215713766959)),
 (2736, np.float64(0.08830215713766959)),
 (3551, np.float64(0.08830215713766959)),
 (479, np.float64(0.08797691788472335)),
 (752, np.float64(0.08749572785196143)),
 (1828, np.float64(0.08749572785196143)),
 (2444, np.float64(0.08746392856766495)),
 (23, np.float64(0.08740748201220976)),
 (141, np.float64(0.08740748201220976)),
 (389, np.float64(0.08740748201220976)),
 (745, np.float64(0.08740748201220976)),
 (794, np.float64(0.08740748201220976)),
 (960, np.float64(0.08740748201220976)),
 (1247, np.float64(0.08740748201220976)),
 (1257, np.float64(0.08740748201220976)),
 (3446, np.float64(0.08740748201220976)),
 (3447, np.float64(0.08740748201220976)),
 (143, np.float64(0.08671099695241201)),
 (199, np.float64(0.08671099695241201)),
 (827, np.float64(0.08671099695241201)),
 (1526, np.float64(0.08671099695241201)),
 (2876, np.float64(0.08671099695241201)),
 (3554, np.float64(0.08671099695241201)),
 (4516, np.float64(0.08671099695241201)),

In [39]:
similarity

array([[1.        , 0.08346223, 0.0860309 , ..., 0.04499213, 0.        ,
        0.        ],
       [0.08346223, 1.        , 0.06063391, ..., 0.02378257, 0.        ,
        0.02615329],
       [0.0860309 , 0.06063391, 1.        , ..., 0.02451452, 0.        ,
        0.        ],
       ...,
       [0.04499213, 0.02378257, 0.02451452, ..., 1.        , 0.03962144,
        0.04229549],
       [0.        , 0.        , 0.        , ..., 0.03962144, 1.        ,
        0.08714204],
       [0.        , 0.02615329, 0.        , ..., 0.04229549, 0.08714204,
        1.        ]], shape=(4806, 4806))

In [40]:
#similartiy[1] is say that the distance between the vecotrs of vector 1 
similarity[1]

array([0.08346223, 1.        , 0.06063391, ..., 0.02378257, 0.        ,
       0.02615329], shape=(4806,))

In [41]:
new_df[new_df['title'] == 'Batman Begins'].index[0]

np.int64(119)

In [42]:
def recommand(movie):
    if movie not in new_df['title'].values:
        print(f"Error: Movie '{movie}' not found in the dataset.")
        return []
    movie_index=new_df[new_df['title'] == movie].index[0]
    distance=similarity[movie_index]
    movie_list=sorted(list(enumerate(distance)),reverse=True,key =lambda x:x[1])[1:6]

    for i in movie_list:
        print(new_df.iloc[i[0]].title)

In [43]:
recommand('Krrish')

Girl 6
My Lucky Star
Inside Deep Throat
Harrison Montgomery
Incident at Loch Ness

In [44]:
import pickle

In [48]:
pickle.dump(similarity,open("similarity.pkl","wb"))

In [45]:
pickle.dump(new_df.to_dict(),open("movies.pkl","wb"))

In [46]:
np.save('similarity.npy', similarity)

In [47]:
new_df.to_pickle('movie_data.pkl')